name: aicaptain
channels:
  - cogsci
  - defaults
dependencies:
  - python=3.6
  - pandas
  - ipykernel
  - nb_conda
  - jupyter
  - matplotlib
  - scikit-learn
  - scikit-image
  - tensorflow
  - keras
  - pip:
    - pygame
    - PyGeodesy